### ISSUE TITLE
Bug: 404 not found for ember-tooltips.css.map

### ISSUE THREAD

**Issue by mayatron** [sir-dunxalot/ember-tooltips#113] opened 2016-11-19 22:51 UTC
The source map request to `/assets/ember-tooltips.css.map` is 404 not found for a clean build with the latest ember cli 2.9.1. Similar to an earlier closed issue https://github.com/sir-dunxalot/ember-tooltips/issues/76.

Steps to reproduce:

```
ember new myapp && cd myapp
ember install ember-tooltips && npm uninstall ember-welcome-page --save-dev
ember s
```

![screen shot 2016-11-19 at 2 33 53 pm](https://cloud.githubusercontent.com/assets/1009725/20458872/bb5596f2-ae65-11e6-87ed-def193475c4f.png)

![screen shot 2016-11-19 at 2 40 11 pm](https://cloud.githubusercontent.com/assets/1009725/20458913/5e835b48-ae66-11e6-9b5f-37940d258e8c.png)

**Comment by a15n** [comment] 2016-12-17 03:00
I have `ember-cli:  2.5.0` but as soon as I created an app I updated to 2.9.1 (not sure that changes anything).

I tried reproducing this but was unable to. The page loads fine for me.

**Comment by sir-dunxalot** [comment] 2016-12-22 19:33
I believe this is a duplicate of #76, which was identified as an upstream issue.

**Closed by sir-dunxalot** 2016-12-22 19:33 UTC
