### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by vastan** [sir-dunxalot/ember-tooltips#238] opened 2018-02-20 11:10 UTC
The error from title appears when I'm trying to add 2 elements that contain tooltips after another ember addon called ember-line-clamp. The error is shown only on multiple elements after the line-clamp addon. It seems to work just fine with only one element to contain the tooltip.

Version 3.0.0 beta 2

Here you can find an example: https://github.com/mihnea-baia/test-ember-tooltips

**Comment by sir-dunxalot** [comment] 2018-10-07 01:57
Thank you for the code! Very helpful. I can confirm I am seeing the error when I run mihnea-baia/test-ember-tooltips locally and the error is gone when removing either the `{{line-clamp}}` component or the `{{ember-tooltip}}` component.

I will investigate the source of the error and report back, hopefully with a PR that fixes this!

**Comment by sir-dunxalot** [comment] 2018-10-07 04:41
This issue has been fixed and is not present with the latest ember-tooltips prerelease, `3.0.0-beta.4`, which you can install using `ember install ember-tooltips@3.0.0-beta.4`.

To be honest, I don't know exactly what fixed this issue and, since everything is green in the latest release, I didn't dig in any further. #286 adds a test to monitor future compatibility with `ember-line-clamp`.

**Comment by sir-dunxalot** [comment] 2018-10-23 14:39
Fixed by #272.

**Closed by sir-dunxalot** 2018-10-23 14:39 UTC
Labels: 3.x, bug
