### ISSUE TITLE
updateFor no longer works when switching to 3.x

### ISSUE THREAD

**Issue by kennydp** [sir-dunxalot/ember-tooltips#371] opened 2019-07-24 09:19 UTC
I am currently updating to 3.3.0 and I have a certain tooltip that uses `updateFor` to rerender. The updateFor no longer has any effect after updating, and it causes the tooltip to be positioned incorrectly after the state changes. I was wondering if it's still possible to do something like the `updateFor` with 3.x?

**Comment by maxfierke** [comment] 2019-07-27 18:20
`updateFor` is still implemented in 3.x. Could you share some more details on how you're using it? Which version are you updating from?

**Comment by kennydp** [comment] 2019-07-29 12:04
I'm updating from 2.11.1 to 3.3.0. 

So, in this particular case, when a tooltip shows we send a request for additional data, so in the tooltips you'll see our loading animation. Once the data is in, we show the actual data. The issue we get is that when the loading state is active, the tooltip is not as high as when the data is there. On the old version the tooltip would be pushed up, while now the tooltip gets put over your cursor.

**Comment by maxfierke** [comment] 2019-07-29 14:29
@kennydp is there some code you can share for a reproducible test case?

**Comment by kennydp** [comment] 2019-07-29 14:55
Yeah sure, I'll try to put it in a twiddle. May only be tomorrow though, not sure if I have time to look into it today.

**Comment by kennydp** [comment] 2019-07-30 06:44
https://ember-twiddle.com/95db34917f2ae1d789361ad337fcd5d3?openFiles=controllers.application.js%2C

Here you can see the issue I'm having. Because the height changes, the tooltip gets pushed over the cursor, while before it would just be placed higher up.

**Comment by maxfierke** [comment] 2019-07-30 14:01
@kennydp ahhh yeah. Thanks for the reproduction! I'll take a look this week!

**Comment by maxfierke** [comment] 2019-07-31 02:25
@kennydp ahhh, found the trick for this: because `isLoading` is `false`, it's not hitting the code path for `updateFor`. The fix for this is that we should just be checking that it's not the default value of `null`. A workaround for the time being would be to return some sort of truthy value, but I'll probably tag a fix tonight

**Closed** 2019-07-31 04:40 UTC
Labels: 3.x, bug
