### ISSUE TITLE
0.x maintenance releases?

### ISSUE THREAD

**Issue by dfreeman** [sir-dunxalot/ember-tooltips#93] opened 2016-09-13 17:57 UTC
Hi! First off, thanks for your work maintaining this addon.

Currently we're stuck on `0.7` until some of the parity loss from the old tooltips plugin (like #82) is regained. Hopefully we'll have a chance to help out with that stuff when time permits, but in the meantime we're having to monkey patch our way around deprecations and incompatibilities in Ember 2.8.

Would you be open to maintaining an `0.x` branch for a while for folks stuck in the same boat as us? No new features or anything, just avoiding errors/deprecations as new Ember releases come out. If you're not opposed to the idea, I'd be happy to open up a PR to kick if off.

**Comment by paultannenbaum** [comment] 2016-09-30 22:37
I am stuck on `07` as I need to keep the `renderTooltip` method for project specifc reasons. I would like to submit a PR to fix deprecation warnings that are caused by the `0.7` in the newest version of Ember (`2.8.1`). Would you accept the PR, or is the `0.7` branch dead?

**Comment by sir-dunxalot** [comment] 2016-10-05 02:04
Hi guys, apologies for the slow response. I am open to maintaining a `0.x` branch - I know a couple of the changes with `1.0.0` were not perfect. I would absolutely accept a PR and we could create the branch off of [this release](https://github.com/sir-dunxalot/ember-tooltips/releases/tag/0.7.0). I suggest adding some documentation for `0.x` users to the Readme in the PR too.

**Comment by sir-dunxalot** [comment] 2016-11-24 00:02
I am closing this issue but we will accept PRs for old major versions.

**Closed by sir-dunxalot** 2016-11-24 00:02 UTC
