### ISSUE TITLE
Positioning the pointer/arrow so it's not always centered in 3.x

### ISSUE THREAD

**Issue by artikhurana** [sir-dunxalot/ember-tooltips#381] opened 2019-10-15 10:31 UTC
I upgraded ember tooltip version 2.x to 3.x and found that tooltip is not centered when I hover on text first time and the snapshot is attached for reference -:

<img width="82" alt="Arrow_not_centered" src="https://user-images.githubusercontent.com/16552468/66823666-53033d00-ef64-11e9-8eca-b2124059e650.png">

After that when I hover again then it is working fine and the snapshot is attached for reference -:

<img width="107" alt="Centered_Align" src="https://user-images.githubusercontent.com/16552468/66823816-a07faa00-ef64-11e9-8f43-063081f8d001.png">

What I believe is that due to lazy loading, the CSS properties are not getting set properly. However, on the next hover, since the element is already present in DOM, the properties get applied correctly.

Any help would be appreciated.

**Comment by maxfierke** [comment] 2019-10-16 19:45
Hi @artikhurana  -- It may depend on the CSS of the parent element(s). Would you be able to share some CSS for those and a snippet of the template surrounding the use of ember-tooltips? Does it exhibit the same behavior when passing `popperContainer="body"` to the tooltip?

**Comment by eramod** [comment] 2020-01-07 18:06
I just installed ember-tooltips and I'm running into this issue as well - the tooltip renders too close to the element it's attached to on the first render, causing it to overlap the element. The difference in the css appears to be that the transform:translate3d property is calculated differently on the tooltip's first render than on subsequent renders.

I tried your suggestion of setting popperContainer="body", but that didn't change it in any way.

**Comment by maxfierke** [comment] 2020-01-08 21:52
Hi @eramod! Thanks for sharing the images! Since those values are calculated and populated by either `popper.js` or `tooltip.js`, so I'll have to dig into those two a bit more to get a sense for what might be happening here.

It _could_ be related to the `escapeWithReference` modifier, which `ember-tooltips` activates by default. Mind giving it a try with that setting disabled? The `popperOptions` section in the README has [an example of how to disable this option](https://github.com/sir-dunxalot/ember-tooltips#popperoptions).

**Comment by rwwagner90** [comment] 2020-01-13 12:34
I'm experiencing this issue as well. Disabling `escapeWithReference` does not change the behavior.

**Comment by maxfierke** [comment] 2020-01-13 15:27
Has this just started occurring recently (e.g. after an Ember upgrade?)

**Comment by rwwagner90** [comment] 2020-01-13 15:34
@maxfierke I am not sure exactly when it started happening. An Ember upgrade or yarn upgrade or something could have triggered it. I do not think it was always a problem, but maybe it was and I just didn't notice.

**Comment by maxfierke** [comment] 2020-01-19 22:17
Hey folks, I looked into this a bit yesterday and it seems like it may have been caused by some change in Ember 3.14 or 3.15 that seems to have been resolved by merging #388 to replace `ember-wormhole` with `ember-maybe-in-element`.

`ember-wormhole` used an `afterRender`-scheduled task (and an observer for changes) to do its positioning of a rendered element vs. the `in-element` helper, which I think does it in the same render cycle. It could also be related to the new async observer defaults in Octane, but that probably wouldn't explain the original poster's concern (or if y'all are not using Octane yet)

I'll try to get new version out in the next day or two.

**Comment by rwwagner90** [comment] 2020-01-20 00:28
@maxfierke I believe I did start seeing the issue only after updating to Octane, so the observer changes sounds like a likely culprit. Thanks for tracking this down!

**Comment by maxfierke** [comment] 2020-01-21 02:29
Released a fix in 3.4.2. Hopefully this also fixes the original issue as well, but if not, let me know and I can re-open this.

**Closed by maxfierke** 2020-01-21 02:29 UTC
Labels: 3.x, bug

**Comment by eramod** [comment] 2020-01-22 18:05
This resolved the issue for me. Thanks!
